### ISSUE TITLE
Promise does not resolve on abortion

### ISSUE THREAD

**Issue by pschuerk** [dfa1234/ngx-image-compress#45]
Hey i don't know if this is a real problem, but i wondered why the promise of .uploadFile() does not resolve or reject, when the user decides to abort the file selection instead of choosing a file.

I would have expected the promise to be rejected in that case.

I am using it like this:
```
async memberFunction(): Promise<void> {
  const compressionInput = await this.customService.uploadImage();
  // code here never gets executed on abortion of the file selection
  ...
}
```

Where the customService just wraps the uploadFile function of the NgxImageCompressService like so:
```
uploadFile(): Promise<CompressionInput> {
  return this.imageCompress.uploadFile();
}
```
Doesn't this mean, that an async thread or something gets stuck waiting for the promise to resolve or be rejected?

Greetings

**Comment by dfa1234** [comment]
If you look [at this try catch](https://github.com/dfa1234/ngx-image-compress/blob/b6438668b8be9e940e6e3abf2604ef382c0a4c24/projects/ngx-image-compress/src/lib/image-compress.ts#L89)

You will see the promise is rejecting when no files are selected / the user abord.

If it's not the case, you can update your issue, I will let it open meanwhile

**Comment by byronigoe** [comment]
Hitting Cancel on the File Picker does not throw an error or trigger any event, so there's no way to know it happened. There are some supposed [workarounds](https://stackoverflow.com/questions/34855400/cancel-event-on-input-type-file), but `click` is the only event that gets triggered the current way uploadFile is implemented. If you implemented your own file input control differently (i.e. a native element instead of an invisible one), then you could try some shenanigans with `focus` and `blur`.

**Comment by byronigoe** [comment]
I've got it working by implementing uploadFile() myself ([copied from here](https://stackoverflow.com/a/63773257/5356670)). The code is almost identical to ImageCompress.uploadFile(), so perhaps using Renderer2 is the reason the focus event isn't emitted.

**Comment by dfa1234** [comment]
I let upload apart the compress to let the user freely choose the upload method. 

Renderer2 seems to be the best option because of reasons https://stackoverflow.com/a/56143045/4406065

But maybe we could add another uploadFile function using direct DOM manipulation as a workaround for your case, that's pretty simple.

**Comment by dfa1234** [comment]
https://github.com/dfa1234/ngx-image-compress/commit/41d36467966b4529cdc1c93d07a16402c92676f6
