### ISSUE TITLE
Compress image to given size

### ISSUE THREAD

**Issue by ruisilva450** [dfa1234/ngx-image-compress#5]
At the description is said: 
"Angular utility for compressing images to a satisfying size, that you can choose"
But you don't seem to be able to choose the target size for the image.

I can only choose the quality from 0-100 to compress and to get the size I want the only way is to try and error until it gives the size I want.

Am I missing something?
Thank you

**Comment by dfa1234** [comment]
Yes you are right, there is something missing... very easy to figure in my opinion but I could have made this more explicit.

In order to decide exactly which size you want, you need to loop (or preferably using a recursive function), to check that you have the expected size.

Following the example on the readme:

You will use 

`this.imageCompress.uploadFile`

only one time, but than you can use

`this.imageCompress.compressFile`
`this.imageCompress.byteCount`

as many time that you need.
