### ISSUE TITLE
how to compress multiple images?

### ISSUE THREAD

**Issue by vinhebbar** [dfa1234/ngx-image-compress#55]
i did not see any documentation,  how to compress multiple images at a time?

**Comment by dfa1234** [comment]
You can't multi-select files right now.
Anyway it's a feature we need to seriously consider, because a multi-upload can take time. You need to design a progress bar, a cancel button etc...
It's for that case that I separated the "upload feature" from the "compress feature".
Feel free to create by yourself a multi-upload, and you can use the compress function into a loop and compress everything at a time.

**Comment by dfa1234** [comment]
Done in version 13+
