### ISSUE TITLE
Doesn't work with version 12 of Angular

### ISSUE THREAD

**Issue by broomfn** [dfa1234/ngx-image-compress#90]
Hi,

I'm trying to use with version 12 of Angular, but you don't appear to have a version that's compatible?
```
$ node --version
v16.15.0
$ npm --version
8.10.0

npm ERR! Conflicting peer dependency: @angular/common@11.2.14
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^11.0.1" from ngx-image-compress@11.0.3
npm ERR!   node_modules/ngx-image-compress
npm ERR!     ngx-image-compress@"^11.0.3" from the root project
```
Any help gratefully received.

Many thanks

Neil

**Comment by broomfn** [comment]
For anyone else with this issue I had to provide these overrides to the package,json

  "overrides": {
    "ngx-image-compress": {
      "@angular/common": "12.2.16",
      "@angular/core": "12.2.16"
    }

**Comment by broomfn** [comment]
Hi @dfa1234 , the problem with version 13.1.10 is that it's targeting version 13 of Angular, I'm unable to upgrade to version 13 as this would require me to also upgrade Ionic to version 6.  Basically you don't appear to have a version of your library that's targeting version 12 of Angular, please correct me if I'm wrong.

**Comment by broomfn** [comment]
> 12 with 12

Where is version 12 of this library please? I can't see it on npm.

**Comment by dfa1234** [comment]
Anyway every version before 13.1.8 should not be used. There is an important fixes because browser like chrome made important changes.
I thinks we need to change the way we ask for version. Any version of angular > 4 should be ok, the library is meanly static javascript anyway.
I'm re opening this and will update soon

**Comment by dfa1234** [comment]
I hope version 13.1.12 now working with angular 12, out of the box, without other shenanigan in package.json

Because angular 13 dropped totally view engine support and compile in Ivy (partial mode) only, we are now officialy dropping support for any version of angular < 9.
9+ only will support. 8 can support but some configuration is needed to optin ivy support. 

Here the recap:

![image](https://user-images.githubusercontent.com/8502517/170033021-2cf4cb82-01cd-4e6d-8460-6ad90637a016.png)
